/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the `SDL' library (-lSDL). */
#define HAVE_LIBSDL 1

/* Define to 1 if you have the `SDL_image' library (-lSDL_image). */
#define HAVE_LIBSDL_IMAGE 1

/* Define to 1 if you have the `SDL_mixer' library (-lSDL_mixer). */
#define HAVE_LIBSDL_MIXER 1

/* Define to 1 if you have the `SDL_ttf' library (-lSDL_ttf). */
#define HAVE_LIBSDL_TTF 1

/* Name of package */
#define PACKAGE "AlThreat"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Version number of package */
#define VERSION "0.1"
